// solid/src/examples/counter.tsx
import { Box } from "@r-tui/solid"
import { createSignal } from "solid-js"

export default function App() {
  const [count, setCount] = createSignal(0)
  setInterval(() => {
    setCount((c) => ++c)
  }, 1000)

  return (
    <Box
      width={"100%"}
      height={"100%"}
      display="flex"
      flexDirection="column"
      justifyContent="center"
      alignItems="center"
    >
      <Box color="red" text={"count"} />
      <Box color="green" text={":"} />
      <Box color="blue" text={`${count()}`} />
    </Box>
  )
}

// ui/src/examples/counter.tsx
import React, { useEffect, useState } from "react"
import { Box } from "../"

export default function App() {
  const [count, setCount] = useState(0)
  useEffect(() => {
    setInterval(() => {
      setCount((c) => ++c)
    }, 1000)
  }, [])
  return (
    <Box
      width={"100%"}
      height={"100%"}
      display="flex"
      flexDirection="column"
      justifyContent="center"
      alignItems="center"
    >
      <Box color="red" text={"count"} />
      <Box color="green" text={":"} />
      <Box color="blue" text={`${count}`} />
    </Box>
  )
}
