// solid/src/hook/input.ts
import { createSignal } from "solid-js"

let init = false
const inputHandleSet = new Set<(s: string) => void>()

export const Enter = "\x0d"
export const CtrlC = "\x03"
export const Left = "\u001b[D"
export const Up = "\u001b[A"
export const Right = "\u001b[C"
export const Down = "\u001b[B"
export const Tab = "\t"

function initMode() {
  if (init) return
  init = true
  process.stdin.setRawMode(true)
  function handleReadable() {
    let s: string | null
    // biome-ignore lint/suspicious/noAssignInExpressions: <explanation>
    while ((s = process.stdin.read()) !== null) {
      const str = s.toString()
      if (str === CtrlC) {
        process.exit()
      }
      for (const fn of inputHandleSet) {
        fn(str)
      }
    }
  }
  process.stdin.addListener("readable", handleReadable)
}

export function onInput(handle: (s: string) => void) {
  initMode()
  inputHandleSet.add(handle)
}
export function offInput(handle: (s: string) => void) {
  initMode()
  inputHandleSet.delete(handle)
}
export function useInput() {
  initMode()
  const [key, setKey] = createSignal<string | undefined>()
  onInput(setKey)
  return key
}

export function useReadLine() {
  const [data, setData] = createSignal<string | undefined>()
  process.stdin.addListener("data", (s) => {
    setData(s.toString().trim())
  })
  return data
}

// react/src/hook/input.ts
import { useEffect, useState } from "react"

let init = false
const inputHandleSet = new Set<(s: string) => void>()

export const Enter = "\x0d"
export const CtrlC = "\x03"
export const Left = "\u001b[D"
export const Up = "\u001b[A"
export const Right = "\u001b[C"
export const Down = "\u001b[B"
export const Tab = "\t"

function initMode() {
  if (init) return
  init = true
  process.stdin.setRawMode(true)
  function handleReadable() {
    let s: string | null
    // biome-ignore lint/suspicious/noAssignInExpressions: <explanation>
    while ((s = process.stdin.read()) !== null) {
      const str = s.toString()
      if (str === CtrlC) {
        process.exit()
      }
      for (const fn of inputHandleSet) {
        fn(str)
      }
    }
  }
  process.stdin.addListener("readable", handleReadable)
}

export function onInput(handle: (s: string) => void) {
  initMode()
  inputHandleSet.add(handle)
}
export function offInput(handle: (s: string) => void) {
  initMode()
  inputHandleSet.delete(handle)
}
export function useInput() {
  initMode()
  const [key, setKey] = useState<string | undefined>()
  useEffect(() => {
    onInput(setKey)
  }, [])
  return key
}

export function useReadLine() {
  const [data, setData] = useState<string | undefined>()
  useEffect(() => {
    process.stdin.addListener("data", (s) => {
      setData(s.toString().trim())
    })
  }, [])
  return data
}
